Enable text selection for Xcode version
XcodesOrg/XcodesApp pull request #416
Opened 2023-08-24 17:50 UTC by yo1995

Close #415

2023-11-22 05:07 UTC, MattKiazyk commented on Xcodes/Frontend/InfoPane/InfoPane.swift
> +                        .textSelection(.enabled)
`.textSelection` is only available on MacOS 12. Currently Xcodes has a minimum version of 11. 

You can either wrap this in a `#available`  or this PR can wait a bit. Some point soon we'll update to min of 12.

2023-11-22 05:42 UTC, MattKiazyk requested changes
Thanks! 

See comment around macOS 12 vs 11

2023-11-22 18:04 UTC, yo1995 commented on Xcodes/Frontend/InfoPane/InfoPane.swift
> +                        .textSelection(.enabled)
Thanks! It was an oversight from my part - I only saw the "build with macOS 12" part in README, but didn't read the "run on macOS 11.0" line 😅 

I'll defer it to your decision - feel free to wait min target becomes macOS 12 or edit this PR with

```swift
private extension InfoPane {
    @ViewBuilder
    func textSelection(_ enabled: Bool) -> some View {
        if #available(macOS 12, *), enabled {
            self
                .textSelection(.enabled)
        } else {
            self
        }
    }
}
```

2024-03-08 20:50 UTC, MattKiazyk commented
This has been added via https://github.com/XcodesOrg/XcodesApp/pull/503

2024-03-08 20:50 UTC, closed without merging