Activity Indicator on Install Pressed
XcodesOrg/XcodesApp pull request #437
Opened 2023-10-17 23:23 UTC by chickdan

I noticed that there is often a long delay between clicking Install and the button switching to the linear progress view which sometimes makes it seem unresponsive. So I added a circular style progress view to the install button to indicate activity and reduce the chance of repeat clicks.

Before:
<img width="77" alt="Screenshot 2023-10-17 at 6 21 21 PM" src="https://github.com/XcodesOrg/XcodesApp/assets/8951682/1f9aabab-4bf1-4fb3-b758-6f3f07b5be62">

After:
<img width="81" alt="Screenshot 2023-10-17 at 6 21 26 PM" src="https://github.com/XcodesOrg/XcodesApp/assets/8951682/39fb9fbe-f63d-4ce3-a6dd-8a819dd03c38">

2023-11-22 05:27 UTC, MattKiazyk requested changes
Thanks @chickdan !

Can we switch it to use `ProgressButton` that we already have?

2023-11-22 05:27 UTC, MattKiazyk commented on Xcodes/Backend/XcodeCommands.swift
>          Button(action: install) {
Can we reuse `ProgressButton` that we have already (2FA/SMS windows)

2023-11-26 01:20 UTC, chickdan commented on Xcodes/Backend/XcodeCommands.swift
>          Button(action: install) {
Updated!

2023-12-01 16:21 UTC, MattKiazyk requested changes

2023-12-05 23:55 UTC, chickdan commented on Xcodes/Backend/XcodeCommands.swift
> +        }.buttonStyle(AppStoreButtonStyle(primary: false, highlighted: false))
Good catch! Updated.

2023-12-13 03:27 UTC, MattKiazyk approved these changes

2023-12-13 03:28 UTC, merged

2023-12-13 03:53 UTC, NSExceptional commented
GitHub pro tip @chickdan: if you put something like `fixes #9999` in the PR title, it'll automatically close the issue when the PR is merged :)