Update zh_Hans Localizations.
XcodesOrg/XcodesApp pull request #482
Opened 2024-01-20 04:42 UTC by megabitsenmzq

1. Add new Localizations. 

- "Alert.CancelInstall.Runtimes.Title"
- "Alert.DeletePlatform.PrimaryButton"
- "Alert.DeletePlatform.Title"
- "Perform post-install steps"
- "Error"
- "Open In Rosetta"
- "Platforms"
- "PlatformsList.Title"

2. Fix some old Localizations. All contains "前置步骤" -> "安装后准备步骤".

3. Remove old or useless Localizations.

4. Create a file "String+.swift" to remove preview strings from localizations.

2024-01-24 04:38 UTC, MattKiazyk reviewed
I'm not seeing the value in adding in the `.hideInLocalizations` unless I'm missing something? Can you elaborate?

2024-01-24 04:38 UTC, MattKiazyk commented on Xcodes/Frontend/Common/String+.swift
> +    var hideInLocalizations: String {
Curious on the benefit of adding this? Is there a places where we would want to do this vs just allowing it to go to the LocalizedStringKey?

2024-01-24 11:23 UTC, megabitsenmzq commented on Xcodes/Frontend/Common/String+.swift
> +    var hideInLocalizations: String {
If you check the other files I modified to add ".hideInLocalizations", you will notice that they are all in previews. These strings are only for preview purposes and don't need to be translated. But they will appear in xcstrings after compiling. So people who do the translation might be confused by this. Actually, I first translated all of them, then found out there was no need to do that.

2024-02-02 04:39 UTC, MattKiazyk requested changes
In researching other localization issues - I came across `Text(verbatim:`
 https://developer.apple.com/documentation/swiftui/text/init(verbatim:) 

Which is a more simpler solution for what you're trying to accomplish so that it doesn't go into the .xcstrings file. 

Can you remove your `hideInLocalizations` variable and replace with verbatim where you want? Thanks

2024-02-02 05:11 UTC, megabitsenmzq commented
Got it! I will try it this weekend.

2024-02-03 13:36 UTC, megabitsenmzq commented
I found that although Text support initializes with init(verbatim: ), Picker or TextField don't have alternatives for this.

2024-02-08 03:30 UTC, megabitsenmzq commented
@MattKiazyk I removed "String+" and modified all Texts to use init(verbatim: ). For "Picker" and "TextField" which are not supporting init(verbatim: ), I gave them labels with Texts. Please check it out.

2024-02-09 15:47 UTC, MattKiazyk commented
@megabitsenmzq thanks so much for those changes - can you just rebase and I'll get that merged in

2024-02-10 06:40 UTC, megabitsenmzq commented
> @megabitsenmzq thanks so much for those changes - can you just rebase and I'll get that merged in

Done!

2024-02-16 15:08 UTC, merged