Improve the layout of the sidebar
XcodesOrg/XcodesApp pull request #504
Opened 2024-02-18 11:08 UTC by huihuisang

**Modification reason:**
The sidebar UI layout looks a bit crowded and asymmetric. ( Maybe it's just my personal subjective feeling. :) )

**This PR makes the following changes:**
1. Added a default icon with transparency to distinguish between downloaded and undownloaded states, and eliminate the blank space on the left when not downloaded.
2. When not downloaded, the version name is centered.
3. Moved platforms to the upper left corner to reduce the display of mismatched buttons at the bottom.

**Before:**
<img width="1012" alt="Screenshot 2024-02-18 at 14 41 37" src="https://github.com/XcodesOrg/XcodesApp/assets/101007168/9ab38d8b-0334-4142-bb63-7114ed74ed8d">

**After:**
<img width="1012" alt="Screenshot 2024-02-18 at 14 42 06" src="https://github.com/XcodesOrg/XcodesApp/assets/101007168/9d59f30a-187c-47e2-baf6-f97160f1dc99">

2024-02-28 17:04 UTC, rtharston commented on Xcodes/Frontend/XcodeList/XcodeListViewRow.swift
> +            Image("xcode")
You could check `xcode.version.isPrerelease` to show "xcode" or "xcode-beta" (and add the beta icon to the assets catalog as well).

```swift
Image(xcode.version.isPrerelease ? "xcode-beta" : "xcode")
```

2024-02-29 00:51 UTC, huihuisang commented on Xcodes/Frontend/XcodeList/XcodeListViewRow.swift
> +            Image("xcode")
Thank you for the great suggestion. I'll update the code accordingly. ^_^

2024-03-08 19:07 UTC, MattKiazyk requested changes
@huihuisang thanks for the work you've done. Totally love the new icons and how it looks. 

Can I ask that you leave the platforms button as it was in the bottom left vs at the top toolbar. 

Because the platforms window is completely separate, having at the top toolbar doesn't make sense as that toolbar filters, searches, etc the list. 

Thanks!

2024-03-08 19:17 UTC, rtharston commented
> Because the platforms window is completely separate, having at the top toolbar doesn't make sense as that toolbar filters, searches, etc the list.

That is a fair point, but it is a bit large and feels a little out of place.
Maybe instead of putting the button in the left section of the toolbar, it could go on the right section, near the account and settings buttons. The settings button also opens a new window.

What do you think?

2024-03-08 20:12 UTC, MattKiazyk commented
> > Because the platforms window is completely separate, having at the top toolbar doesn't make sense as that toolbar filters, searches, etc the list.
> 
> That is a fair point, but it is a bit large and feels a little out of place. Maybe instead of putting the button in the left section of the toolbar, it could go on the right section, near the account and settings buttons. The settings button also opens a new window.
> 
> What do you think?

I'm still leaning towards having it on the left side vs having another icon on the right. Perhaps smaller?

2024-03-08 20:48 UTC, rtharston commented
Hmm... I'm not UI designer, so I don't have the tools to mock up some options.

I think my main issue with the current Platforms button is that it is alone and feels out of place. Making it big makes it easy to spot, but why is it in the list of Xcode versions? 🤷‍♂️

Thinking about that gave me another thought. Why do the platforms need to be a different window? Could there be a tab selector instead that switched between Xcode and Platform in the left column? The platforms window is just showing a list after all, and that list could fit there.
That then leads to the question of what to put in the detail view when a platform is selected.

Okay, sanity check. I just opened Xcodes to remind myself what is in the Platforms window. It is only the installed platforms. I think my tabbed left column idea only makes sense if it shows all available platforms, similar to the Xcode list.

Probably best to revert it for this PR, as you suggest, and discuss this elsewhere so the approved parts can get merged.

2024-03-10 07:50 UTC, huihuisang commented
> @huihuisang thanks for the work you've done. Totally love the new icons and how it looks.
> 
> Can I ask that you leave the platforms button as it was in the bottom left vs at the top toolbar.
> 
> Because the platforms window is completely separate, having at the top toolbar doesn't make sense as that toolbar filters, searches, etc the list.
> 
> Thanks!

Thank you for your reply. Actually, I don't have a better idea of where this feature should be placed either. The initial modification was just because I felt it looked a bit awkward and took up space at the bottom of the list. Putting it in the top-left corner was to solve this issue. Initially, I also considered that putting it together with the filter button in the top-left corner might not be appropriate. Since I don't have a better idea for now, based on your suggestion, I'll put it back in its original position and make some minor style adjustments so that it doesn't look too abrupt.

2024-03-15 16:22 UTC, MattKiazyk commented
Thanks for the back and forth and the changes - appreciate it!

I _may_ change the `Installed Platforms` later as I'm working on that platforms view to be more then just the installed ones, but for now 👍

2024-03-15 16:23 UTC, merged

2024-03-15 16:27 UTC, MattKiazyk commented
Another Change that would be awesome now is that putting that same default icon on the xcode detail view.

![Screenshot 2024-03-15 at 11 27 23 AM](https://github.com/XcodesOrg/XcodesApp/assets/1119565/912ea6b1-8fb3-4aee-8043-056d5771a27a)

2024-03-16 10:02 UTC, huihuisang commented
> Another Change that would be awesome now is that putting that same default icon on the xcode detail view.
> 
> ![Screenshot 2024-03-15 at 11 27 23 AM](https://private-user-images.githubusercontent.com/1119565/313264948-912ea6b1-8fb3-4aee-8043-056d5771a27a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1ODM0NDksIm5iZiI6MTcxMDU4MzE0OSwicGF0aCI6Ii8xMTE5NTY1LzMxMzI2NDk0OC05MTJlYTZiMS04ZmIzLTRhZWUtODA0My0wNTZkNTc3MWEyN2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTZUMDk1OTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjk5YTI2MzE5ZDMzYmUwNmY5ZjFmYTgyZjZkODM5NWIxZTkwZGZlNWJkYWYwMWViYjg1ZmY1YTVjMTgzZDU5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jwyLCPnQ3Mu0RgjyDCU8D6ga3LYRQ45v54vfb3RF_hY)

👌 I'll add it later～