Add `isProcessing(id: Xcode.ID) -> Bool` to the AppState
XcodesOrg/XcodesApp pull request #613
Opened 2024-09-22 08:19 UTC by chuganzy

Thanks for creating this awesome app!

This PR aims to fix a minor issue where it keeps displaying the indicator on the install button on error.
To fix it, this PR introduces `isProcessing(id: Xcode.ID) -> Bool` to the AppState, and marks `installationPublishers` `@Published`.

## Performance

Unfortunately by marking `installationPublishers` `@Published`, it now also triggers the UI update when installation is initiated. I personally believe this is not a big problem as any other state changes such as Xcode's installation state changes also trigger it anyway, but please let me know if there is any concern.

## Screen Capture

### Before

https://github.com/user-attachments/assets/12efaa2d-51ef-42ff-8fb4-5d0035f61c14

### After

https://github.com/user-attachments/assets/5f61257c-2806-4179-b495-20afd2a5e20f

2024-09-22 09:13 UTC, chuganzy commented on Xcodes/Resources/Localizable.xcstrings
> +            "value" : "認証中"
Added only Japanese as I am a native speaker, but want the community help for others!

2024-10-11 16:07 UTC, MattKiazyk requested changes
Can we please add `Authenticating` as the value for all languages? This will be default for all languages and needs to be unfortunately added

2024-10-11 16:07 UTC, MattKiazyk commented
Thanks @chuganzy - just one change with adding the localization values for all the languages. 🙏

2024-10-13 02:15 UTC, merged

2024-10-13 04:11 UTC, chuganzy commented
@MattKiazyk Thank you for reviewing!